version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data  
    ports:
      - '5432:5432'
  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR     
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      BUNDLE_PATH: /bundle # 追加箇所
      API_DOMAIN: "localhost:$FRONT_PORT" 
    volumes:
      - ./api:/$WORKDIR   
      - bundle_path:/bundle # 追加箇所
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
 
  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT" 
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api
volumes:
  bundle_path: # 追加箇所